In [164]:
import pandas as pd
import numpy as np

In [166]:
dataset=pd.read_csv("50_Startups.csv")

In [168]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [170]:
independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]

In [172]:
dependent=dataset[['Profit']]

In [174]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [176]:
#Standardisation
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [178]:
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)

In [180]:
#to save the sc model
from pickle import dump,load
dump(sc,open('StandardScaler1.pkl','wb'))


In [182]:
#to load the sc model
sc=load(open('StandardScaler1.pkl','rb'))

In [184]:
#to save the scy model
dump(scy,open('StandardScaler2.pkl','wb'))

In [186]:
#to load the scy model
scy=load(open('StandardScaler2.pkl','rb'))

In [188]:
#model creation
from sklearn.svm import SVR
regressor=SVR(kernel="rbf",C=1000)
regressor.fit(x_train,y_train)

C:\Users\keert\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1000)

In [190]:
#to display the intercept and support 
regressor.intercept_

array([-0.18199713])

In [192]:
regressor.n_support_

array([26])

In [194]:
#Evaluation metrics
y_pred=regressor.predict(x_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.635256697420611

In [196]:
#to save the model
import pickle
filename="finalized_model_svmpio.sav"
pickle.dump(regressor,open(filename,'wb'))

In [198]:
preinput=sc.transform([[1300,12000,4000,0,1]])

C:\Users\keert\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [200]:
loaded_model=pickle.load(open("finalized_model_svmpio.sav",'rb'))
result=loaded_model.predict(preinput)
result

array([-1.03109284])

In [202]:
preoutput=scy.inverse_transform([result])
preoutput

array([[65875.16964031]])